theme: jekyll-theme-leap-day
title: ZI Zoraez

navbar:
  - title: Home
    href: https://zi-youtuber.github.io/My-Website-2/
  - title: About
    href: https://zi-youtuber.github.io/My-Website-2/about
  - title: Repos
    href: https://zi-youtuber.github.io/My-Website-2/repos
